version: '3.5'

services:
  redis:
    image: 'redis:alpine'
    command: --port 6380
    ports:
      - '6380:6380'
    expose:
      - '6380'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - '8082:8081'
    depends_on:
      - redis
  admin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - base_network
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  db:
    image: mysql:5.7
    networks:
      - base_network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

networks:
  base_network:

volumes:
  db_data:
